### PR TITLE
completion for 'oc adm' commands

### PR DESCRIPTION
**Pull request by vbehar**
@chmouel if you have some time to review, because I don't have your zsh-completion skills ;-)

I'm not a big fan of the __oc_adm_subcommand function that re-parse for the groups and policy subcommands, so if you know a better way of doing that...

### CODE REVIEW

**Comment by chmouel** [comment]
nice work! I don't think there is better way to do that unfortunately without a rewrite. We should use contexts and state more (i.e: http://wikimatze.de/writing-zsh-completion-for-padrino) and we may be able to generate on the fly completion as well coupled with caching, I started to work on it but it was too much of a pain and I gave up :-\

**Comment by chmouel** [comment]
i have tested and it's working well btw so 👍

**Comment by vbehar** [comment]
yes generated completion is the goal !

**Comment by chmouel** [comment]
we can maybe as well fix spf13/cobra to support zsh  i.e: adapting : 

https://github.com/spf13/cobra/blob/master/bash_completions.go

I may have a go at it as well when I got time, last time I fall out unconscious out of boreness and PHP flashbacks reading shell/go mixed code

**Pull request merged**
